\hypertarget{classpy_1_1__code_1_1__assertionnew_1_1_failure}{}\section{py.\+\_\+code.\+\_\+assertionnew.\+Failure Class Reference}
\label{classpy_1_1__code_1_1__assertionnew_1_1_failure}\index{py.\+\_\+code.\+\_\+assertionnew.\+Failure@{py.\+\_\+code.\+\_\+assertionnew.\+Failure}}


Inherits Exception.

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classpy_1_1__code_1_1__assertionnew_1_1_failure_ad87da4e9ffb8cc14581d53393c28e912}\label{classpy_1_1__code_1_1__assertionnew_1_1_failure_ad87da4e9ffb8cc14581d53393c28e912}} 
def {\bfseries \+\_\+\+\_\+init\+\_\+\+\_\+} (self, explanation=\char`\"{}\char`\"{})
\end{DoxyCompactItemize}
\subsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classpy_1_1__code_1_1__assertionnew_1_1_failure_a5a7d2bb6eb3f474273718738d6819470}\label{classpy_1_1__code_1_1__assertionnew_1_1_failure_a5a7d2bb6eb3f474273718738d6819470}} 
{\bfseries cause}
\item 
\mbox{\Hypertarget{classpy_1_1__code_1_1__assertionnew_1_1_failure_a836fcd6b8a80dcb322b1306c6ed7a239}\label{classpy_1_1__code_1_1__assertionnew_1_1_failure_a836fcd6b8a80dcb322b1306c6ed7a239}} 
{\bfseries explanation}
\end{DoxyCompactItemize}


\subsection{Detailed Description}
\begin{DoxyVerb}Error found while interpreting AST.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+6/site-\/packages/py/\+\_\+code/\+\_\+assertionnew.\+py\end{DoxyCompactItemize}
