\hypertarget{classgevent_1_1exceptions_1_1_blocking_switch_out_error}{}\section{gevent.\+exceptions.\+Blocking\+Switch\+Out\+Error Class Reference}
\label{classgevent_1_1exceptions_1_1_blocking_switch_out_error}\index{gevent.\+exceptions.\+Blocking\+Switch\+Out\+Error@{gevent.\+exceptions.\+Blocking\+Switch\+Out\+Error}}


Inherits Assertion\+Error.



\subsection{Detailed Description}
\begin{DoxyVerb}Raised when a gevent synchronous function is called from a
low-level event loop callback.

This is usually a programming error.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+6/site-\/packages/gevent/exceptions.\+py\end{DoxyCompactItemize}
