\hypertarget{class__pytest_1_1doctest_1_1_multiple_doctest_failures}{}\section{\+\_\+pytest.\+doctest.\+Multiple\+Doctest\+Failures Class Reference}
\label{class__pytest_1_1doctest_1_1_multiple_doctest_failures}\index{\+\_\+pytest.\+doctest.\+Multiple\+Doctest\+Failures@{\+\_\+pytest.\+doctest.\+Multiple\+Doctest\+Failures}}


Inherits Exception.

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{class__pytest_1_1doctest_1_1_multiple_doctest_failures_a0a14b147a4b06bddb247c36bdbbf3500}\label{class__pytest_1_1doctest_1_1_multiple_doctest_failures_a0a14b147a4b06bddb247c36bdbbf3500}} 
def {\bfseries \+\_\+\+\_\+init\+\_\+\+\_\+} (self, failures)
\end{DoxyCompactItemize}
\subsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{class__pytest_1_1doctest_1_1_multiple_doctest_failures_a0388fd8a02bec4b1ac9fb1d1a5a035fd}\label{class__pytest_1_1doctest_1_1_multiple_doctest_failures_a0388fd8a02bec4b1ac9fb1d1a5a035fd}} 
{\bfseries failures}
\end{DoxyCompactItemize}


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+6/site-\/packages/\+\_\+pytest/doctest.\+py\end{DoxyCompactItemize}
