\hypertarget{namespace__pytest_1_1python__api}{}\section{\+\_\+pytest.\+python\+\_\+api Namespace Reference}
\label{namespace__pytest_1_1python__api}\index{\+\_\+pytest.\+python\+\_\+api@{\+\_\+pytest.\+python\+\_\+api}}
\subsection*{Classes}
\begin{DoxyCompactItemize}
\item 
class \hyperlink{class__pytest_1_1python__api_1_1_approx_base}{Approx\+Base}
\item 
class \hyperlink{class__pytest_1_1python__api_1_1_approx_decimal}{Approx\+Decimal}
\item 
class \hyperlink{class__pytest_1_1python__api_1_1_approx_mapping}{Approx\+Mapping}
\item 
class \hyperlink{class__pytest_1_1python__api_1_1_approx_numpy}{Approx\+Numpy}
\item 
class \hyperlink{class__pytest_1_1python__api_1_1_approx_scalar}{Approx\+Scalar}
\item 
class \hyperlink{class__pytest_1_1python__api_1_1_approx_sequence}{Approx\+Sequence}
\item 
class \hyperlink{class__pytest_1_1python__api_1_1_raises_context}{Raises\+Context}
\end{DoxyCompactItemize}
\subsection*{Functions}
\begin{DoxyCompactItemize}
\item 
def \hyperlink{namespace__pytest_1_1python__api_a70e8904dd5c406d57f3cb4897d02830c}{approx} (expected, rel=None, abs=None, nan\+\_\+ok=False)
\item 
def \hyperlink{namespace__pytest_1_1python__api_aaa3a9d5e292629d192415ffdb2843bc3}{raises} (expected\+\_\+exception, args, kwargs)
\end{DoxyCompactItemize}
\subsection*{Variables}
\begin{DoxyCompactItemize}
\item 
tuple \hyperlink{namespace__pytest_1_1python__api_acd2ec62d4c43de74a8a0ef7eb1829f5f}{B\+A\+S\+E\+\_\+\+T\+Y\+PE} = (type, S\+T\+R\+I\+N\+G\+\_\+\+T\+Y\+P\+ES)
\end{DoxyCompactItemize}


\subsection{Function Documentation}
\mbox{\Hypertarget{namespace__pytest_1_1python__api_a70e8904dd5c406d57f3cb4897d02830c}\label{namespace__pytest_1_1python__api_a70e8904dd5c406d57f3cb4897d02830c}} 
\index{\+\_\+pytest\+::python\+\_\+api@{\+\_\+pytest\+::python\+\_\+api}!approx@{approx}}
\index{approx@{approx}!\+\_\+pytest\+::python\+\_\+api@{\+\_\+pytest\+::python\+\_\+api}}
\subsubsection{\texorpdfstring{approx()}{approx()}}
{\footnotesize\ttfamily def \+\_\+pytest.\+python\+\_\+api.\+approx (\begin{DoxyParamCaption}\item[{}]{expected,  }\item[{}]{rel = {\ttfamily None},  }\item[{}]{abs = {\ttfamily None},  }\item[{}]{nan\+\_\+ok = {\ttfamily False} }\end{DoxyParamCaption})}

\begin{DoxyVerb}Assert that two numbers (or two sets of numbers) are equal to each other
within some tolerance.

Due to the `intricacies of floating-point arithmetic`__, numbers that we
would intuitively expect to be equal are not always so::

    >>> 0.1 + 0.2 == 0.3
    False

__ https://docs.python.org/3/tutorial/floatingpoint.html

This problem is commonly encountered when writing tests, e.g. when making
sure that floating-point values are what you expect them to be.  One way to
deal with this problem is to assert that two floating-point numbers are
equal to within some appropriate tolerance::

    >>> abs((0.1 + 0.2) - 0.3) < 1e-6
    True

However, comparisons like this are tedious to write and difficult to
understand.  Furthermore, absolute comparisons like the one above are
usually discouraged because there's no tolerance that works well for all
situations.  ``1e-6`` is good for numbers around ``1``, but too small for
very big numbers and too big for very small ones.  It's better to express
the tolerance as a fraction of the expected value, but relative comparisons
like that are even more difficult to write correctly and concisely.

The ``approx`` class performs floating-point comparisons using a syntax
that's as intuitive as possible::

    >>> from pytest import approx
    >>> 0.1 + 0.2 == approx(0.3)
    True

The same syntax also works for sequences of numbers::

    >>> (0.1 + 0.2, 0.2 + 0.4) == approx((0.3, 0.6))
    True

Dictionary *values*::

    >>> {'a': 0.1 + 0.2, 'b': 0.2 + 0.4} == approx({'a': 0.3, 'b': 0.6})
    True

``numpy`` arrays::

    >>> import numpy as np                                                          # doctest: +SKIP
    >>> np.array([0.1, 0.2]) + np.array([0.2, 0.4]) == approx(np.array([0.3, 0.6])) # doctest: +SKIP
    True

And for a ``numpy`` array against a scalar::

    >>> import numpy as np                                         # doctest: +SKIP
    >>> np.array([0.1, 0.2]) + np.array([0.2, 0.1]) == approx(0.3) # doctest: +SKIP
    True

By default, ``approx`` considers numbers within a relative tolerance of
``1e-6`` (i.e. one part in a million) of its expected value to be equal.
This treatment would lead to surprising results if the expected value was
``0.0``, because nothing but ``0.0`` itself is relatively close to ``0.0``.
To handle this case less surprisingly, ``approx`` also considers numbers
within an absolute tolerance of ``1e-12`` of its expected value to be
equal.  Infinity and NaN are special cases.  Infinity is only considered
equal to itself, regardless of the relative tolerance.  NaN is not
considered equal to anything by default, but you can make it be equal to
itself by setting the ``nan_ok`` argument to True.  (This is meant to
facilitate comparing arrays that use NaN to mean "no data".)

Both the relative and absolute tolerances can be changed by passing
arguments to the ``approx`` constructor::

    >>> 1.0001 == approx(1)
    False
    >>> 1.0001 == approx(1, rel=1e-3)
    True
    >>> 1.0001 == approx(1, abs=1e-3)
    True

If you specify ``abs`` but not ``rel``, the comparison will not consider
the relative tolerance at all.  In other words, two numbers that are within
the default relative tolerance of ``1e-6`` will still be considered unequal
if they exceed the specified absolute tolerance.  If you specify both
``abs`` and ``rel``, the numbers will be considered equal if either
tolerance is met::

    >>> 1 + 1e-8 == approx(1)
    True
    >>> 1 + 1e-8 == approx(1, abs=1e-12)
    False
    >>> 1 + 1e-8 == approx(1, rel=1e-6, abs=1e-12)
    True

If you're thinking about using ``approx``, then you might want to know how
it compares to other good ways of comparing floating-point numbers.  All of
these algorithms are based on relative and absolute tolerances and should
agree for the most part, but they do have meaningful differences:

- ``math.isclose(a, b, rel_tol=1e-9, abs_tol=0.0)``:  True if the relative
  tolerance is met w.r.t. either ``a`` or ``b`` or if the absolute
  tolerance is met.  Because the relative tolerance is calculated w.r.t.
  both ``a`` and ``b``, this test is symmetric (i.e.  neither ``a`` nor
  ``b`` is a "reference value").  You have to specify an absolute tolerance
  if you want to compare to ``0.0`` because there is no tolerance by
  default.  Only available in python>=3.5.  `More information...`__

  __ https://docs.python.org/3/library/math.html#math.isclose

- ``numpy.isclose(a, b, rtol=1e-5, atol=1e-8)``: True if the difference
  between ``a`` and ``b`` is less that the sum of the relative tolerance
  w.r.t. ``b`` and the absolute tolerance.  Because the relative tolerance
  is only calculated w.r.t. ``b``, this test is asymmetric and you can
  think of ``b`` as the reference value.  Support for comparing sequences
  is provided by ``numpy.allclose``.  `More information...`__

  __ http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.isclose.html

- ``unittest.TestCase.assertAlmostEqual(a, b)``: True if ``a`` and ``b``
  are within an absolute tolerance of ``1e-7``.  No relative tolerance is
  considered and the absolute tolerance cannot be changed, so this function
  is not appropriate for very large or very small numbers.  Also, it's only
  available in subclasses of ``unittest.TestCase`` and it's ugly because it
  doesn't follow PEP8.  `More information...`__

  __ https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual

- ``a == pytest.approx(b, rel=1e-6, abs=1e-12)``: True if the relative
  tolerance is met w.r.t. ``b`` or if the absolute tolerance is met.
  Because the relative tolerance is only calculated w.r.t. ``b``, this test
  is asymmetric and you can think of ``b`` as the reference value.  In the
  special case that you explicitly specify an absolute tolerance but not a
  relative tolerance, only the absolute tolerance is considered.

.. warning::

   .. versionchanged:: 3.2

   In order to avoid inconsistent behavior, ``TypeError`` is
   raised for ``>``, ``>=``, ``<`` and ``<=`` comparisons.
   The example below illustrates the problem::

       assert approx(0.1) > 0.1 + 1e-10  # calls approx(0.1).__gt__(0.1 + 1e-10)
       assert 0.1 + 1e-10 > approx(0.1)  # calls approx(0.1).__lt__(0.1 + 1e-10)

   In the second example one expects ``approx(0.1).__le__(0.1 + 1e-10)``
   to be called. But instead, ``approx(0.1).__lt__(0.1 + 1e-10)`` is used to
   comparison. This is because the call hierarchy of rich comparisons
   follows a fixed behavior. `More information...`__

   __ https://docs.python.org/3/reference/datamodel.html#object.__ge__
\end{DoxyVerb}
 \mbox{\Hypertarget{namespace__pytest_1_1python__api_aaa3a9d5e292629d192415ffdb2843bc3}\label{namespace__pytest_1_1python__api_aaa3a9d5e292629d192415ffdb2843bc3}} 
\index{\+\_\+pytest\+::python\+\_\+api@{\+\_\+pytest\+::python\+\_\+api}!raises@{raises}}
\index{raises@{raises}!\+\_\+pytest\+::python\+\_\+api@{\+\_\+pytest\+::python\+\_\+api}}
\subsubsection{\texorpdfstring{raises()}{raises()}}
{\footnotesize\ttfamily def \+\_\+pytest.\+python\+\_\+api.\+raises (\begin{DoxyParamCaption}\item[{}]{expected\+\_\+exception,  }\item[{}]{args,  }\item[{}]{kwargs }\end{DoxyParamCaption})}

\begin{DoxyVerb}Assert that a code block/function call raises ``expected_exception``
and raise a failure exception otherwise.

:arg message: if specified, provides a custom failure message if the
    exception is not raised
:arg match: if specified, asserts that the exception matches a text or regex

This helper produces a ``ExceptionInfo()`` object (see below).

You may use this function as a context manager::

    >>> with raises(ZeroDivisionError):
    ...    1/0

.. versionchanged:: 2.10

In the context manager form you may use the keyword argument
``message`` to specify a custom failure message::

    >>> with raises(ZeroDivisionError, message="Expecting ZeroDivisionError"):
    ...    pass
    Traceback (most recent call last):
      ...
    Failed: Expecting ZeroDivisionError

.. note::

   When using ``pytest.raises`` as a context manager, it's worthwhile to
   note that normal context manager rules apply and that the exception
   raised *must* be the final line in the scope of the context manager.
   Lines of code after that, within the scope of the context manager will
   not be executed. For example::

       >>> value = 15
       >>> with raises(ValueError) as exc_info:
       ...     if value > 10:
       ...         raise ValueError("value must be <= 10")
       ...     assert exc_info.type == ValueError  # this will not execute

   Instead, the following approach must be taken (note the difference in
   scope)::

       >>> with raises(ValueError) as exc_info:
       ...     if value > 10:
       ...         raise ValueError("value must be <= 10")
       ...
       >>> assert exc_info.type == ValueError


Since version ``3.1`` you can use the keyword argument ``match`` to assert that the
exception matches a text or regex::

    >>> with raises(ValueError, match='must be 0 or None'):
    ...     raise ValueError("value must be 0 or None")

    >>> with raises(ValueError, match=r'must be \d+$'):
    ...     raise ValueError("value must be 42")

**Legacy forms**

The forms below are fully supported but are discouraged for new code because the
context manager form is regarded as more readable and less error-prone.

It is possible to specify a callable by passing a to-be-called lambda::

    >>> raises(ZeroDivisionError, lambda: 1/0)
    <ExceptionInfo ...>

or you can specify an arbitrary callable with arguments::

    >>> def f(x): return 1/x
    ...
    >>> raises(ZeroDivisionError, f, 0)
    <ExceptionInfo ...>
    >>> raises(ZeroDivisionError, f, x=0)
    <ExceptionInfo ...>

It is also possible to pass a string to be evaluated at runtime::

    >>> raises(ZeroDivisionError, "f(0)")
    <ExceptionInfo ...>

The string will be evaluated using the same ``locals()`` and ``globals()``
at the moment of the ``raises`` call.

.. currentmodule:: _pytest._code

Consult the API of ``excinfo`` objects: :class:`ExceptionInfo`.

.. note::
    Similar to caught exception objects in Python, explicitly clearing
    local references to returned ``ExceptionInfo`` objects can
    help the Python interpreter speed up its garbage collection.

    Clearing those references breaks a reference cycle
    (``ExceptionInfo`` --> caught exception --> frame stack raising
    the exception --> current frame stack --> local variables -->
    ``ExceptionInfo``) which makes Python keep all objects referenced
    from that cycle (including all local variables in the current
    frame) alive until the next cyclic garbage collection run. See the
    official Python ``try`` statement documentation for more detailed
    information.\end{DoxyVerb}
 

\subsection{Variable Documentation}
\mbox{\Hypertarget{namespace__pytest_1_1python__api_acd2ec62d4c43de74a8a0ef7eb1829f5f}\label{namespace__pytest_1_1python__api_acd2ec62d4c43de74a8a0ef7eb1829f5f}} 
\index{\+\_\+pytest\+::python\+\_\+api@{\+\_\+pytest\+::python\+\_\+api}!B\+A\+S\+E\+\_\+\+T\+Y\+PE@{B\+A\+S\+E\+\_\+\+T\+Y\+PE}}
\index{B\+A\+S\+E\+\_\+\+T\+Y\+PE@{B\+A\+S\+E\+\_\+\+T\+Y\+PE}!\+\_\+pytest\+::python\+\_\+api@{\+\_\+pytest\+::python\+\_\+api}}
\subsubsection{\texorpdfstring{B\+A\+S\+E\+\_\+\+T\+Y\+PE}{BASE\_TYPE}}
{\footnotesize\ttfamily tuple \+\_\+pytest.\+python\+\_\+api.\+B\+A\+S\+E\+\_\+\+T\+Y\+PE = (type, S\+T\+R\+I\+N\+G\+\_\+\+T\+Y\+P\+ES)}

